### ISSUE TITLE
Create a random number generator using python.

### ISSUE THREAD

**Issue by sat5297** [sat5297/hacktober-coding#13]

**Comment by Developer-R-7** [comment]
Feel ,good to contribute to this repo
i have just updated the random number python file in your repo with commented code and basic knowledge of namespaces in python

hope ,you will accept the pull requests

### Happy coding!!

**Comment by Kishan-Sahu** [comment]
I want to contribute can you assign it to me.

**Comment by sat5297** [comment]
Yeah go ahead.

**Comment by Kishan-Sahu** [comment]
@sat5297  i had submitted the file ,plese accept the pull request.
