### ISSUE TITLE
Check if a number is power of 2.

### ISSUE THREAD

**Issue by sat5297** [sat5297/hacktober-coding#187]

**Comment by saptarsi96** [comment]
I will work on it.

**Comment by AnkitaM84** [comment]
@sat5297  It would be great if you could add hacktoberfest-coding label to these issues.

**Comment by TusharSharmaIN** [comment]
Please assign this to me. I want to do this.

**Comment by priyalgupta09** [comment]
hello . please assign this to me . I will work on it

**Comment by saptarsi96** [comment]
Hi All, Change has been completed as per PR [#189](https://github.com/sat5297/hacktober-coding/pull/189/commits/5fd3b17fb6234c9b5d527494f21ad381ca3ccb61)

**Comment by sat5297** [comment]
All of you can do it. ****The label says no need to seek permission****

**Comment by PODU** [comment]
I would like to work on it.

**Comment by Riuregan** [comment]
Hi can you assign me to this issue?
Thanks!
