### ISSUE TITLE
 Program for Sum of squares of first n natural numbers

### ISSUE THREAD

**Issue by sat5297** [sat5297/hacktober-coding#29]

**Comment by rahul-s-bhatt** [comment]
Hey,
can you assign this to me?

**Comment by gaurangisinha** [comment]
Hello, @sat5297 Could you please assign this to me, I am very keen on contributing to this issue.

**Comment by sat5297** [comment]
Go ahead.

**Comment by gaurangisinha** [comment]
> Go ahead.

Could I solve this in python or C?

**Comment by sat5297** [comment]
Yeah.
