### ISSUE TITLE
Add HacktoberFest hacktoberfest2020 to the topics

### ISSUE THREAD

**Issue by parth93QA** [sat5297/hacktober-coding#57]

**Comment by aj-923** [comment]
yep that would be great, since hacktoberfest rules have been changed inn order to minimize spam PRs. Any PR made to this repo won't count unless your repo has "hacktoberfest" as a topic and a submitted PR is tagged as "hacktoberfest-accepted" or the PR is merged.

**Comment by sat5297** [comment]
@aj-923  ok so I will add that in the issues.

**Comment by sat5297** [comment]
ok so whats the best thing that can be done in that context.

**Comment by aj-923** [comment]
Hey I think it would help a lot just if you add the "hacktoberfest" topic
to your repo and keep merging PRs as soon as possible.

**Comment by sat5297** [comment]
Done

**Comment by sat5297** [comment]
@aj-923 I have modified it. Check on your end once.

**Comment by aj-923** [comment]
Thanks! Would you like me to contribute to something specific to your repo?
I would love to help you out.

**Comment by sat5297** [comment]
@aj-923 I think we can create more good first issues for others. And anything that can be of help is appreciated. You can think on your end.
