### ISSUE TITLE
LCM of Two Numbers

### ISSUE THREAD

**Issue by sat5297** [sat5297/hacktober-coding#76]

**Comment by gaurangisinha** [comment]
Hello, @sat5297  Could you please assign this to me, I am very keen on contributing to this issue.

**Comment by sat5297** [comment]
Go ahead.

**Comment by Sayantan-world** [comment]
Hey can I contribute the code in Java for this issue

**Comment by gaurangisinha** [comment]
@sat5297 Could I solve this in python?

**Comment by sat5297** [comment]
Yes.
