### ISSUE TITLE
Program to reverse words in a String

### ISSUE THREAD

**Issue by sat5297** [sat5297/hacktober-coding#79]

**Comment by vkgupta857** [comment]
Please provide sample cases so that others can understand the problem more clearly.

**Comment by vkgupta857** [comment]
Although, it is clear from the title but sample cases will give more clarification.

**Comment by sat5297** [comment]
the fox ate the fruit
fruit the ate fox the

**Comment by AlessandroArosio** [comment]
@sat5297 can I do this in Java?
