### ISSUE TITLE
 Program to Calculate Area of Rectangle, Square, Circle. (use Switch case)

### ISSUE THREAD

**Issue by sat5297** [sat5297/hacktober-coding#82]

**Comment by mrcodedev** [comment]
I want take this issue, thanks 👍

**Comment by AlessandroArosio** [comment]
Hi @sat5297 , can you assign this to me? I can use the new switch from JDK12+

**Comment by Sayantan-world** [comment]
Can I do it in C++? Please assign this to me.

**Comment by sat5297** [comment]
Yes guys. Go ahead.
