### ISSUE TITLE
Program to make a calculator using switch case

### ISSUE THREAD

**Issue by sat5297** [sat5297/hacktober-coding#83]

**Comment by kshitij5** [comment]
I just added a basic Calculator program in Java language #93

**Comment by sat5297** [comment]
ok.

**Comment by Sayantan-world** [comment]
Can you assign this to me, I want to make a contribution in C++.

**Comment by sat5297** [comment]
yeah. Go ahead.

**Comment by nikita812** [comment]
hey i want to do this in python. please assign

**Comment by sat5297** [comment]
Yeah Go ahead.
